### ISSUE TITLE
command 'gitProjectManager.openProject' not found

### ISSUE THREAD

**Issue by FezVrasta** [felipecaputo/git-project-manager#53] opened 2017-05-25 16:32 UTC
Sometimes I get this error when I try to open the list of projects.

```
command 'gitProjectManager.openProject' not found
```

Restarting VS Code fixed the problem

**Comment by felipecaputo** [comment] 2017-06-05 10:59
Hi @FezVrasta, sorry for taking too long. 

I'll take a look at this. Did you notice any sequence of steps that leads to this error?

**Comment by FezVrasta** [comment] 2017-06-05 11:07
It happens as soon I open a new VS Code instance

**Comment by sgtoj** [comment] 2017-08-07 13:01
This is now an issue with current VS Code Insiders. It has been for the past week or two. 

### Troubleshooting

- Reinstall the Add-on
- Reinstall VS Code Insiders
- Both 32 and 64 bit Insiders versions fail
- Standard VS Code works expected

### Version Info

#### System Information

- Windows 10 Insiders - Build 16257 (latest)
- NodeJS v8.2.1

#### VS Code Insiders 

```
Version 1.15.0-insider
Commit 6feff11ed03402cf77e04e74e13c55529fdb4d09
Date 2017-08-04T17:53:03.136Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
Architecture x64
```

**Comment by felipecaputo** [comment] 2017-08-07 13:33
@sgtoj Thanks for the Trobleshooting.

I'll take some time to understand why this is happening, maybe some problema between previous updates.

I'll try to update using vsix and reproduce the error. o/

**Comment by sgtoj** [comment] 2017-08-09 14:44
@felipecaputo 
The solution I found was uninstalling VS Code Insiders then deleting `%USERPROFILE%\AppData\Roaming` directory then reinstalling VS Code Insiders.

**Comment by felipecaputo** [comment] 2017-08-24 01:21
@sgtoj, I had the same problem with the last update of Python extension from Don Jayamane recently, but I didn't had to delete the folder.

Did the problem occurred any time after that update?

**Comment by sgtoj** [comment] 2017-08-24 15:23
@felipecaputo Nope. Just this one so far. I use that same extension nearly daily too.

**Comment by felipecaputo** [comment] 2018-03-29 15:13
I'm closing this issue since the problem seems to stop happening. 

If it happens again, feel free to open it again.

**Comment by Goddak** [comment] 2018-05-30 11:01
@felipecaputo - My colleague @fullas has started seeing this problem today, I'll provide some detail below;

OS Ver: Linux - Ubuntu 16.04
VSC Ver: 1.23.1
GPM Ver: 1.6.1

We're unable to perform any actions and simply get errors like;
- `gitProjectManager.newWindow` cannot be found.
- `gitProjectManager.openProject` cannot be found.

We have taken these basic steps to resolve the problem;
- Shutdown & reboot OS
- Close & open VSCode
- Uninstall extension, reload, reinstall, reload
- Uninstall extension, reload, close VSCode, open VSCode, install, reload
- *Other similar actions*

To our knowledge there were no VSCode updates installed today.

**Comment by felipecaputo** [comment] 2018-05-31 18:14
It looks like there is something that after some updates, something breaks in the extension folder... Could you please validate if there is any private data on it, and if don't compress it and attach here for me to be able to reproduce and try to fix it?

**Closed** 2018-08-20 13:12 UTC
Labels: bug, help wanted

**Comment by Goddak** [comment] 2018-10-02 11:48
> It looks like there is something that after some updates, something breaks in the extension folder... Could you please validate if there is any private data on it, and if don't compress it and attach here for me to be able to reproduce and try to fix it?

Just seen this, sorry bud, glad you got it sorted :smile:
