### ISSUE TITLE
Error while showing Project list: TypeError: e.done is not a function

### ISSUE THREAD

**Issue by ksfe** [felipecaputo/git-project-manager#9] opened 2016-09-09 07:47 UTC
Error while showing Project list: TypeError: e.done is not a function!!  For vs code v1.5.1

**Comment by admiral0** [comment] 2016-09-09 10:49
Duplicate of #8

**Comment by felipecaputo** [comment] 2016-09-12 11:52
ShowQuickPick is not working when receive promises.

Version 0.1.14 fixes it, but as a side efect, quick pick will not be shown until all folders had been searched.

**Closed by felipecaputo** 2016-09-12 11:52 UTC

**Comment by ksfe** [comment] 2016-09-13 07:46
Thx all!
